//
// SwfCategory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum SwfCategory: String, Codable, CaseIterable {
    case waifu = "waifu"
    case neko = "neko"
    case shinobu = "shinobu"
    case megumin = "megumin"
    case bully = "bully"
    case cuddle = "cuddle"
    case cry = "cry"
    case hug = "hug"
    case awoo = "awoo"
    case kiss = "kiss"
    case lick = "lick"
    case pat = "pat"
    case smug = "smug"
    case bonk = "bonk"
    case yeet = "yeet"
    case blush = "blush"
    case smile = "smile"
    case wave = "wave"
    case highfive = "highfive"
    case handhold = "handhold"
    case nom = "nom"
    case bite = "bite"
    case glomp = "glomp"
    case slap = "slap"
    case kill = "kill"
    case kick = "kick"
    case happy = "happy"
    case wink = "wink"
    case poke = "poke"
    case dance = "dance"
    case cringe = "cringe"
}
