openapi: 3.0.3
info:
  title: animechanApi
  description: |-
    https://animechan.vercel.app
    This service return quotes from anime titles 
    You can search quotes randomly or by Anime titles or characters
  version: 1.0.0
servers:
- url: https://animechan.vercel.app/api
  description: Main server
- url: http://animechan.melosh.space
  description: Second server
tags: 
- name: animeQuotes
  description: quotes
paths:
  /quotes:
    get:
      tags: 
        - animeQuotes
      summary: Get 10 random quotes
      operationId: randomQuotes
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuoteArray'
        default:
          description: enexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
  /quotes/anime:
    get:
      tags: 
        - animeQuotes
      summary: Get 10 random quotes from Anime Title
      operationId: randomQuotesByAnime
      parameters: 
        - in: query
          name: title 
          required: true
          schema: 
            type: "string"
          description: "anime name"
        - in: query
          name: page
          schema: 
            type: "integer"
          description: "page"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuoteArray'
        default:
          description: enexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
  /quotes/character:
    get:
      tags: 
        - animeQuotes    
      summary: Get 10 radnom quotes by anime character
      operationId: randomQuotesByCharacter
      parameters: 
        - in: query
          name: name 
          required: true
          schema: 
            type: "string"
          description: "character name"
        - in: query
          name: page
          schema: 
            type: "integer"
          description: "page"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuoteArray'
        default:
          description: enexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'                
  /random:
    get:
      tags: 
        - animeQuotes    
      summary: Get a random quote
      operationId: randomQuote
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
        default:
          description: enexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
  /random/anime: 
    get: 
      tags: 
        - animeQuotes    
      summary: randomQuoteByAnimeCharacter
      operationId: randomQuoteByAnimeTitle
      parameters: 
            - in: query
              name: title
              schema: 
                type: "string"
              description: "anime name"
              required: true
      responses: 
        "200": 
          description: OK 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
        default:
          description: enexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
  /random/character:
    get: 
      tags: 
        - animeQuotes    
      summary: randomQuoteByAnimeCharacter
      operationId: randomQuoteByAnimeCharacter
      parameters: 
            - in: query
              name: name 
              schema: 
                type: "string"
              description: "character name"
              required: true
      responses: 
        "200": 
          description: OK 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
        default:
          description: enexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
  /available/anime:
    get: 
      tags: 
        - animeQuotes    
      summary: Anime Array
      operationId: animeArray
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnimeArray'
        default:
          description: enexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
  /available/character:
    get: 
      tags: 
        - animeQuotes    
      summary: CharacterArray
      operationId: characterArray
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CharacterArray'
        default:
          description: enexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
components:
  schemas:
    QuoteArray: 
      type: array
      items: 
        $ref: '#/components/schemas/Quote'
    Quote:
      required: 
      - key
      - anime
      - character
      - quote
      - __v
      properties: 
        key: 
          type: "number"
        anime: 
          type: "string"
        character: 
          type: "string"
        quote: 
          type: "string"
        __v: 
          type: "number"
    AnimeArray: 
      type: array
      items: 
        type: "string"
    CharacterArray: 
      type: array
      items: 
        type: "string"
    ErrorModel:
      required: 
        - "error"
      properties: 
        error: 
          type: "string"
