//
// Quote.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Quote: Codable, JSONEncodable, Hashable {
    
    public var key: Double
    public var anime: String
    public var character: String
    public var quote: String
    public var v: Double
    
    public init(key: Double, anime: String, character: String, quote: String, v: Double) {
        self.key = key
        self.anime = anime
        self.character = character
        self.quote = quote
        self.v = v
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case key
        case anime
        case character
        case quote
        case v = "__v"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(key, forKey: .key)
        try container.encode(anime, forKey: .anime)
        try container.encode(character, forKey: .character)
        try container.encode(quote, forKey: .quote)
        try container.encode(v, forKey: .v)
    }
}

